import excel "C:\Users\micah\OneDrive\Documents\Side Work\Data Analysis\Mr Stafford PhD analysis\PCA\Results MICAH.xlsx",sheet("Sheet1") firstrow

save data1, replace 

use data1, clear 

mdesc /*identify missing data*/

******************************************************************
**DEMOGRAPHICS****
rename AGEGP Age
rename YRSINPRAC Practice_yrs
rename PRACTYP Practice_type

**Institution of qualification 
lab def Institution 0 "In SA" 1 "Outside SA"
lab val Institution Institution
drop if Institution == . 
tab Institution,m 

**Age group 
lab def Age 0 "18-25" 1 "26-35" 2 "36-50" 3 ">50"
lab val Age Age 
tab Age,m 

**Years in practice 
lab def Practice_yrs 1 "<1" 2 "2-5 years" 3 "6-10 years" 4 ">11 years"
lab val Practice_yrs Practice_yrs
tab Practice_yrs,m 

**What type of practice
lab def Practice_type 0 "Mixed practice" 1 "Equine only"
lab val Practice_type Practice_type
tab Practice_type,m 

**What is your sex 
lab def Sex 0 "Male" 1 "Female"
lab val Sex Sex 
tab Sex,m 

***********************************************************************
**KNOWLEDGE**

**Not sufficiently familiar with ESWT
rename SAFFIFAM SB6
replace SB6 = . if SB6 == 5 
tab SB6,m 

**Original use of ESWT was used in human medicine
rename ORIGUSE SB7 
bro if SB7 == .
drop if SB7 == . // 6 individuals cannot continue with the questionnnaire 
tab SB7,m 

//Change "I do not know" == . for analysis
replace SB7 = . if SB7 == 2 
replace SB7 = 2 if SB7 == 3
replace SB7 = 3 if SB7 == 4 
tab SB7, m 

**The current use of ESWT is based on understanding that it has regenerative effect 
rename REGENEFF SB8
tab SB8, m 

replace SB8 = . if SB8 == 2 
replace SB8 = 2 if SB8 == 3
replace SB8 = 3 if SB8 == 4 
tab SB8, m 

**The standard protocol for ESWT on tendon and ligaments is 3 sessions, 2 weeks apart 
rename STANPROT SB9
replace SB9 = . if SB9 == 5
tab SB9, m 

replace SB9 = . if SB9 == 2 
replace SB9 = 2 if SB9 == 3
replace SB9 = 3 if SB9 == 4 
tab SB9, m 

**The current protocol used for treatment of tendons and ligaments is based on extensive scientific research 
rename SCIENRES SB10
replace SB10 = . if SB10 == 5
tab SB10,m 

replace SB10 = . if SB10 == 2 
replace SB10 = 2 if SB10 == 3
replace SB10 = 3 if SB10 == 4 
tab SB10, m 

**The principle physiological effect of ESWT is a mechanical force resulting in tissue cavitation
rename PHYSEFF SB11
replace SB11 = . if SB11 == 5
tab SB11,m 

replace SB11 = . if SB11 == 2 
replace SB11 = 2 if SB11 == 3
replace SB11 = 3 if SB11 == 4 
tab SB11, m 

**ESWT has the most usage with treating tendons/ligaments
rename USAG SB12
replace SB12 = . if SB12 == 5
tab SB12,m 

replace SB12 = . if SB12 == 2 
replace SB12 = 2 if SB12 == 3
replace SB12 = 3 if SB12 == 4 
tab SB12, m 

**ESWT induces a strong analgesic effect in injured tendons
rename ANALEFF SB13
tab SB13,m 

replace SB13 = . if SB13 == 2 
replace SB13 = 2 if SB13 == 3
replace SB13 = 3 if SB13 == 4 
tab SB13, m 

**ESWT increases vascularization in damaged tissue on which it is applied 
rename VASCDAM SB14
tab SB14,m 

replace SB14 = . if SB14 == 2 
replace SB14 = 2 if SB14 == 3
replace SB14 = 3 if SB14 == 4 
tab SB14, m 

**There is meaningful angiogenesis in tendons/ligaments of equines treated with ESWT.
rename ANGIOGEN SB15
tab SB15,m 

replace SB15 = . if SB15 == 2 
replace SB15 = 2 if SB15 == 3
replace SB15 = 3 if SB15 == 4 
tab SB15, m 

**The radial ESWT soundwave is more powerful than the focused ESWT soundwave.
rename RADMORPOW SB16
tab SB16,m 

replace SB16 = . if SB16 == 2 
replace SB16 = 2 if SB16 == 3
replace SB16 = 3 if SB16 == 4 
tab SB16, m 

**Radial waves are generated by a pneumatic force
rename RADPNEU SB17
replace SB17 = . if SB17 ==5 
tab SB17,m 

replace SB17 = . if SB17 == 2 
replace SB17 = 2 if SB17 == 3
replace SB17 = 3 if SB17 == 4 
tab SB17, m 

**Focused waves are generated by an electric 
rename FOCELECT SB18
replace SB18 = . if SB18 == 5
tab SB18,m 

replace SB18 = . if SB18 == 2 
replace SB18 = 2 if SB18 == 3
replace SB18 = 3 if SB18 == 4 
tab SB18, m 

**Radial ESWT, when compared to Focused ESWT is a less less specific/accurate targeted wave.
rename RADLESSSPEC SB19
replace SB19 = . if SB19 == 5 
tab SB19,m 

replace SB19 = . if SB19 == 2 
replace SB19 = 2 if SB19 == 3
replace SB19 = 3 if SB19 == 4 
tab SB19, m 

**Use of the focussed ESWT machine on tendons/ligaments must be be done in conjunction with ultrasound analysis.
rename FOCCONULTRA SB20
replace SB20 = . if SB20 == 5
tab SB20, m 

replace SB20 = . if SB20 == 2 
replace SB20 = 2 if SB20 == 3
replace SB20 = 3 if SB20 == 4 
tab SB20, m 

**Overuse of waves from the Focussed ESWT cannot cause injury to healthy tissue
rename FOCDAM SB21
replace SB21 = . if SB21 == 5
tab SB21,m 

replace SB21 = . if SB21 == 2 
replace SB21 = 2 if SB21 == 3
replace SB21 = 3 if SB21 == 4 
tab SB21, m 

**Through overuse, waves from the Radial ESWT can cause injury to healthy tissue
rename RADDAM SB22
replace SB22 = . if SB22 == 5 
tab SB22,m 

replace SB22 = . if SB22 == 2 
replace SB22 = 2 if SB22 == 3
replace SB22 = 3 if SB22 == 4 
tab SB22, m 

**The bar pressure for the focussed ESWT waves are 10-100 times greater than radial waves 
rename FOCBARPRES SB23
replace SB23 = . if SB23 == 5
tab SB23,m 

replace SB23 = . if SB23 == 2 
replace SB23 = 2 if SB23 == 3
replace SB23 = 3 if SB23 == 4 
tab SB23, m 

**The Fédération Éxquestre Internationale (FEI) and the Jockey Club's ruling of banning ESWT prior to sporting events is based on specific scientific research.
rename FEIBAN SB24
tab SB24,m 

replace SB24 = . if SB24 == 2 
replace SB24 = 2 if SB24 == 3
replace SB24 = 3 if SB24 == 4 
tab SB24, m 

use data2, clear 

//Cronbach's alpha evaluates whether the items within a test are consistent in measuring the same thing. It ranges from 0 to 1, with higher values indicating greater internal consistency.
//Generate overall variable - This is typically done to create a composite score that reflects the overall construct being measured by the items.

alpha SB7 SB8 SB9 SB11 SB16 SB17 SB18 SB19 SB21 SB22 SB23 SB24, rev(SB7 SB8 SB9 SB11 SB17 SB18 SB19 SB23) item 
// Already Exclude Qns 6,14,15
//alpha = 0.6012
//these items are consistent in measuring the knowledge score. 

**Find average score 
gen variable = 3
gen rev_SB7 = variable - SB7
gen rev_SB8 = variable - SB8
gen rev_SB9 = variable - SB9
gen rev_SB11 = variable - SB11
gen rev_SB17 = variable - SB17
gen rev_SB18 = variable - SB18
gen rev_SB19 = variable - SB19
gen rev_SB23 = variable - SB23

*bro SB7 rev_SB7 SB11 rev_SB11 SB23 rev_SB23

egen know_mean = rowmean(rev_SB7 rev_SB8 rev_SB9 rev_SB11 SB16 rev_SB17 rev_SB18 rev_SB19 SB21 SB22 rev_SB23 SB24)

*bro Report_ID rev_SB7 rev_SB8 rev_SB9 rev_SB11 SB16 rev_SB17 rev_SB18 rev_SB19 SB21 SB22 rev_SB23 SB24 know_mean

tabstat know_mean, statistics(mean n) //above above score 1.5

**************************************************************ATTITUDES******

**I have no problem recommending ESWT is for the treatment of equine tendons/ligaments.
rename REC SC25
replace SC25 = . if SC25 == 5
tab SC25,m 

replace SC25 = . if SC25 == 2 
replace SC25 = 2 if SC25 == 3
replace SC25 = 3 if SC25 == 4 
tab SC25, m 

**ESWT is effective in treating equine Kissing spine 
rename KISSSPINE SC26
replace SC26 = . if SC26 == 5 
tab SC26,m 

replace SC26 = . if SC26 == 2 
replace SC26 = 2 if SC26 == 3
replace SC26 = 3 if SC26 == 4 
tab SC26, m 

**ESWT is effective in treating equine navicular disease
rename NAVDIS SC27
replace SC27 = . if SC27 == 5 
tab SC27,m 

replace SC27 = . if SC27 == 2 
replace SC27 = 2 if SC27 == 3
replace SC27 = 3 if SC27 == 4 
tab SC27, m 

**ESWT can be used as an adjunct in the treatment protocol of degenerative joint disease.
rename DEGJOIN SC28
tab SC28,m

replace SC28 = . if SC28 == 2 
replace SC28 = 2 if SC28 == 3
replace SC28 = 3 if SC28 == 4 
tab SC28, m 

**Between the Radial ESWT and the  Focussed ESWT, the Radial ESWT is the preferred of the two.
rename RADORFOC SC29
replace SC29 = . if SC29 == 5 
tab SC29,m 

replace SC29 = . if SC29 == 2 
replace SC29 = 2 if SC29 == 3
replace SC29 = 3 if SC29 == 4 
tab SC29, m 

**It is important to keep up to date with the current scientific research on equine ESWT.
rename SCIRES SC30
replace SC30 = . if SC30 == 5 
tab SC30,m

replace SC30 = . if SC30 == 2 
replace SC30 = 2 if SC30 == 3
replace SC30 = 3 if SC30 == 4 
tab SC30, m 

**There is no difference between the Radial and focused ESWT treatments and as a result, they can be used on the same types of injuries.
rename NODIFF SC31
tab SC31,m 

replace SC31 = . if SC31 == 2 
replace SC31 = 2 if SC31 == 3
replace SC31 = 3 if SC31 == 4 
tab SC31, m 

**Most equine  practises should have access to ESWT as part of the treatment protocol for treating injured horses.
rename ACCESWT SC32
replace SC32 = . if SC32 == 5 
tab SC32,m

replace SC32 = . if SC32 == 2 
replace SC32 = 2 if SC32 == 3
replace SC32 = 3 if SC32 == 4 
tab SC32, m 

**The ESWT machine can be used to treat chronic tendon and ligament injuries
rename CHRONTENLIG SC33
tab SC33,m 

replace SC33 = . if SC33 == 2 
replace SC33 = 2 if SC33 == 3
replace SC33 = 3 if SC33 == 4 
tab SC33, m 

alpha SC25 SC26 SC27 SC28 SC30 SC31 SC32 SC33, rev(SC25 SC26 SC27 SC28 SC30 SC32 SC33) item 
//moderately relability, alpha = 0.6117

**Find average score
gen rev_SC25 = variable - SC25
gen rev_SC26 = variable - SC26 
gen rev_SC27 = variable - SC27
gen rev_SC28 = variable - SC28
gen rev_SC30 = variable - SC30
gen rev_SC32 = variable - SC32
gen rev_SC33 = variable - SC33

*bro SC25 rev_SC25 SC28 rev_SC28 SC33 rev_SC33

egen Attitude_mean = rowmean(rev_SC25 rev_SC26 rev_SC27 rev_SC28 rev_SC30 SC31 rev_SC32 rev_SC33)

*bro rev_SC25 rev_SC26 rev_SC27 rev_SC28 rev_SC30 SC31 rev_SC32 rev_SC33 Attitude_mean

tabstat Attitude_mean, statistics(n mean)

************************************************************************PRACTICES*************

**Our practice owns a shockwave machine
rename OWNESWT SD34
replace SD34 = . if SD34 == 5 
replace SD34 = . if SD34 == 2 
tab SD34,m 

**I Prefer referring cases that require treatment with ESWT than handle them myself.
rename REFESWT SD35
replace SD35 = . if SD35 == 5 
replace SD35 = . if SD35 == 2 
replace SD35 = 2 if SD35 == 3
replace SD35 = 3 if SD35 == 4 
tab SD35,m 

**Cases presented with tendon injuries to our practices are always/often treated using ESWT.
rename TENDESWT SD36
replace SD36 = . if SD36 == 5 
replace SD36 = . if SD36 == 2 
replace SD36 = 2 if SD36 == 3
replace SD36 = 3 if SD36 == 4 
tab SD36,m 

**Cases presented to our practice with Kissing Spine injuries are usually treated with ESWT
rename KISSSPINETRE SD37
replace SD37 = . if SD37 == 5 
replace SD37 = . if SD37 == 2 
replace SD37 = 2 if SD37 == 3
replace SD37 = 3 if SD37 == 4 
tab SD37,m 

**I take advantage of analgesic effects of ESWT when treating relevant injuries 
rename ANAL SD38
replace SD38 = . if SD38 == 5 
replace SD38 = . if SD38 == 2 
replace SD38 = 2 if SD38 == 3
replace SD38 = 3 if SD38 == 4 
tab SD38,m 

**There is a standard protocol for treatment of all tendon/ligment injuries using the ESWT.
rename STNDPROT SD39
replace SD39 = . if SD39 == 5 
replace SD39 = . if SD39 == 2 
replace SD39 = 2 if SD39 == 3
replace SD39 = 3 if SD39 == 4 
tab SD39,m 

**My recommendation for treatment of equine injuries using radial and focused ESWT varies depending on the injury and/or issue
rename RECOMVARY SD40
replace SD40 = . if SD40 == 5 
replace SD40 = . if SD40 == 2 
replace SD40 = 2 if SD40 == 3
replace SD40 = 3 if SD40 == 4 
tab SD40,m 

**In our practice we generally follow the recommended protocol of 3 sessions 2 weeks apart.
rename SESS2WEE SD41
replace SD41 = "5" in 16
destring SD41, replace  
replace SD41 = . if SD41 == 5 
replace SD41 = . if SD41 == 2 
replace SD41 = 2 if SD41 == 3
replace SD41 = 3 if SD41 == 4 
tab SD41,m 

alpha SD36 SD37 SD40 SD41, rev(SD36 SD37 SD40 SD41) item //alpha = 0.6002

**Find average score
gen rev_SD36 = variable - SD36
gen rev_SD37 = variable - SD37
gen rev_SD40 = variable - SD40
gen rev_SD41 = variable - SD41

bro rev_SD36 rev_SD37 rev_SD40 rev_SD41

egen practice_mean = rowmean(rev_SD36 rev_SD37 rev_SD40 rev_SD41)

bro Report_ID rev_SD36 rev_SD37 rev_SD40 rev_SD41 practice_mean

tabstat practice_mean, statistics(n mean)

save data2, replace 

**********************************************************

************Regression analysis*****************
*****KNOWLEDGE******

sdtest know_mean, by(Institution) //therefore, use t-test  
ttest know_mean, by(Institution) //no means difference
****

oneway know_mean Age, tabulate //no means difference 
****

oneway know_mean Practice_yrs, tabulate //no means difference
****

sdtest know_mean, by(Practice_type) //therefore, use t-test 
ttest know_mean, by(Practice_type) //no mean difference
****

sdtest know_mean, by(Sex) //use t-test 
ttest know_mean, by(Sex) //no difference 
****

set showbaselevels all
regress know_mean i.Institution i.Age i.Practice_yrs i.Practice_type i.Sex 

predict knowfit 
predict knowresid, rstu 

scatter knowresid knowfit
hettest  
hist knowresid, norm 

******ATTITUDES******

sdtest Attitude_mean, by(Institution) //therefore, use t-test  
ttest Attitude_mean, by(Institution) //no means difference
****

oneway Attitude_mean Age, tabulate //no means difference 
****

oneway Attitude_mean Practice_yrs, tabulate //no means difference
****

sdtest Attitude_mean, by(Practice_type) 
ttest Attitude_mean, by(Practice_type) //no mean difference
****

sdtest Attitude_mean, by(Sex) //use t-test 
ttest Attitude_mean, by(Sex) //no difference 
****

set showbaselevels all
*regress Attitude_mean i.Institution i.Age i.Practice_yrs i.Practice_type i.Sex
regress Attitude_mean i.Institution i.Age i.Practice_yrs i.Sex

testparm i.Age
testparm i.Practice_yrs
testparm i.Sex

predict attitudefit 
predict attituderesid, rstu 

scatter attituderesid attitudefit
hettest 
hist attituderesid,norm  
qnorm attituderesid

//ID 16 & 17 are outliers
hist attituderesid if Report_ID != 1017,norm  
*hist knowresid if Report_ID != 1016,norm  

bro Attitude_mean know_mean if (Report_ID == 1017 | Report_ID == 1016) 
*drop if Report_ID == 1016
drop if Report_ID == 1017 


*****PRACTICES************

sdtest practice_mean, by(Institution) //therefore, use t-test  
ttest practice_mean, by(Institution) //no means difference
****

oneway practice_mean Age, tabulate //no means difference 
****

oneway practice_mean Practice_yrs, tabulate //no means difference
****

sdtest practice_mean, by(Practice_type) //therefore, not use t-test 
tabstat practice_mean, by(Practice_type) statistics(p50 IQR)
ranksum practice_mean, by(Practice_type)
****

sdtest practice_mean, by(Sex) //use t-test 
ttest practice_mean, by(Sex) //no difference 
****
 
*********************************************************














